version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hr-postgres
    environment:
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
      POSTGRES_DB: hr_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    networks:
      - hr-net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: hr-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - hr-net

volumes:
  pgdata:

networks:
  hr-net:
    driver: bridge


